### ISSUE TITLE
SIP for multi-file checksum algorithm

### ISSUE THREAD

**Issue by ritave** [MetaMask/SIPs#123]
In the future we'd like to use [Decentralised Identifiers](https://www.w3.org/TR/did-core/) to refer to Snaps.

It's going to use multi-file checksum that we write to `snap.manfiest.json`, like so `did:snap:8uciDR11gmEm8QDs/sHYPeICmkpHOE4qVe+7zF0O7Ew=`.

The checksum algorithm is currently standardised only in [`snap-utils`](https://github.com/MetaMask/snaps/blob/main/packages/snaps-utils/src/checksum.ts) and is based on [`fast-json-stable-stringify`](https://github.com/MetaMask/snaps/blob/6e0257741c7eb0fb71df5826fcfabb7658abd03e/packages/snaps-utils/src/snaps.ts#L165) npm package.

We should write a SIP that provides all steps to make such a reproducible checksum

**Comment by ritave** [comment]
Alternatively we could move to [JSON Canonicalization Scheme](https://www.rfc-editor.org/rfc/rfc8785#section-appendix.a)

**Comment by astralblue** [comment]
I second JCS; one less standard for us to maintain.
