### ISSUE TITLE
SIP-2 accounts should support wildcard network support

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/SIPs#84]
SIP-2 currently specifies a specific list of chains per account.
An EOA is available on any number of EVM-compatible networks.

We should make sure there's a way for a custom account snap to declare themselves as compatible with any chain of a type that is added in the future!

**Comment by ritave** [comment]
Closing the issue because the API that is SIP-2 based is currently deprecated.

MetaMask is still working on providing Snaps with access to accounts, but that work will be a separate API and SIP.
